# Hockney pool-house wallpaper.

preload = /home/jonathan/.config/wallpapers/hockney-poolhouse-v3.png

wallpaper {
    monitor = Virtual-1
    path = /home/jonathan/.config/wallpapers/hockney-poolhouse-v3.png
}

splash = false
